services:
  postgres:
    container_name: llumini-postgres
    image: postgres
    hostname: localhost
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=llumini_db
      - PGDATA=/data/postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: llumini-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

volumes:
  postgres-data:
